module.exports = {
    express: require('express'),
    path: require('path'),
    cookieParser: require('cookie-parser'),
    bodyParser: require('body-parser'),
    logger: require('morgan'),
    createError: require('http-errors'),
    cors: require('cors'),
    passport: require('passport'),
    JwtStrategy: require('passport-jwt').Strategy,
    ExtractJwt: require('passport-jwt').ExtractJwt,
    bcrypt: require('bcrypt'),
    jwt: require('jsonwebtoken'),
    jsCookie: require('js-cookie'),
    moment: require('moment'),
    util: require("util"),
    promisify: require('util').promisify,
    uuidv1: require('uuidv1'),
    fs: require('fs'),
    url: require('url'),
    low: require('lowdb'),
    FileSync: require('lowdb/adapters/FileSync'),
    multer: require("multer"),
    multerS3: require('multer-s3'),
    randToken: require('rand-token'),
}